version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=olx_monitor
      - DB_USERNAME=olx_monitor
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - APP_URL=${APP_URL}
    networks:
      - olx-monitor-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/runtimes/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - olx-monitor-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - olx-monitor-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=olx_monitor
      - MYSQL_USER=olx_monitor
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root_secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - olx-monitor-network

networks:
  olx-monitor-network:
    driver: bridge

volumes:
  mysql_data:
